services:
  next:
    build: .
    container_name: ecolo-site
    ports:
      - 3000:3000
    restart: always
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 90s
